"use client";
import { useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";
import { authFetch, openAuthenticatedFile } from "../lib/supabase";

type DeletionRequest = { id: string; requestedAt: string; scheduledFor: string };

export function AccountSettings({user,onClose}:{user:User;onClose:()=>void}) {
  const [name,setName]=useState(String(user.user_metadata?.full_name||"")),[email,setEmail]=useState(user.email||""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[deletion,setDeletion]=useState<DeletionRequest|null>(null),[confirmation,setConfirmation]=useState(""),[deletionError,setDeletionError]=useState("");
  useEffect(()=>{let active=true;authFetch("/api/account-deletion").then(response=>response.json()).then((body:{request?:DeletionRequest|null})=>{if(active)setDeletion(body.request??null);});return()=>{active=false;};},[]);
  const save=async()=>{setBusy(true);setMessage("");const {error}=await supabase.auth.updateUser({email,data:{full_name:name},...(password?{password}:{})});setBusy(false);setMessage(error?error.message:email!==user.email?"Check your new email address to confirm the change.":"Account settings saved.");};
  const requestDeletion=async()=>{setBusy(true);setDeletionError("");const response=await authFetch("/api/account-deletion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});const body=await response.json() as {request?:DeletionRequest;error?:string};setBusy(false);if(!response.ok||!body.request){setDeletionError(body.error??"Unable to request deletion.");return;}setDeletion(body.request);setConfirmation("");};
  const cancelDeletion=async()=>{setBusy(true);const response=await authFetch("/api/account-deletion",{method:"DELETE"});setBusy(false);if(response.ok){setDeletion(null);setDeletionError("");}else setDeletionError("Unable to cancel the deletion request.");};
  const providers=(user.app_metadata?.providers as string[]|undefined)??[user.app_metadata?.provider].filter(Boolean);
  return <div className="modal-backdrop"><section className="record-modal account-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><p className="section-label">POSTCARE ACCOUNT</p><h2>Account settings</h2></div><button aria-label="Close" onClick={onClose}>×</button></div><p className="form-guidance">Manage the identity and data controls connected to your permanent PostCare patient account.</p><form onSubmit={event=>{event.preventDefault();void save();}}><label>Full name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Email address<input type="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label>New password <span className="muted">Leave blank to keep the current password</span><input type="password" minLength={8} value={password} onChange={event=>setPassword(event.target.value)}/></label><div className="form-note"><span>✓</span><p><strong>Connected sign-in methods</strong>{providers.map(provider=>provider==="email"?"Email/password":provider[0].toUpperCase()+provider.slice(1)).join(" · ")}</p></div>{message&&<p className={message.includes("saved")||message.startsWith("Check")?"auth-success":"form-error"}>{message}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save changes"}</button></div></form><section className="account-data-controls"><div><p className="section-label">YOUR DATA</p><h3>Export or delete your account</h3><p>Download a portable copy before requesting deletion. Deletion requests have a 14-day recovery period.</p></div><button className="secondary" onClick={()=>{void openAuthenticatedFile("/api/export?format=json");}}>Download my data</button>{deletion?<div className="deletion-pending"><strong>Deletion scheduled for {new Date(deletion.scheduledFor).toLocaleDateString()}</strong><p>Your PostCare data remains available during the recovery period. Cancel the request anytime before this date.</p><button className="secondary" disabled={busy} onClick={()=>{void cancelDeletion();}}>Cancel deletion request</button></div>:<div className="deletion-request"><label>Enter {user.email} to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} /></label>{deletionError&&<p className="form-error">{deletionError}</p>}<button className="danger-button" disabled={busy||confirmation.toLowerCase()!==user.email?.toLowerCase()} onClick={()=>{void requestDeletion();}}>Request account deletion</button></div>}</section></section></div>;
}
