"use client";
import type { Appointment } from "../lib/types";
import { Badge } from "./ui";
import { downloadAppointmentCalendar } from "../lib/calendar";

function when(value: string) { return new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }); }

export function AppointmentsView({ appointments, status, error, onAdd, onEdit, onStatus }: { appointments: Appointment[]; status: "loading" | "ready" | "unavailable"; error: string; onAdd: () => void; onEdit: (appointment: Appointment) => void; onStatus: (appointment: Appointment, action: "cancel" | "complete") => void }) {
  const scheduled = appointments.filter(item => item.status === "scheduled");
  const history = appointments.filter(item => item.status !== "scheduled").sort((a,b) => b.startsAt.localeCompare(a.startsAt));
  return <><header className="page-heading"><div><p className="kicker">YOUR CARE SCHEDULE</p><h1>Appointments</h1><p>Keep upcoming visits, preparation details, and completed care together.</p></div><button className="primary" onClick={onAdd}>＋ Add appointment</button></header>{error && <div className="data-notice">{error}</div>}<section className="section-block"><div className="section-heading"><div><p className="section-label">UPCOMING</p><h2>Scheduled appointments</h2></div><span className={`storage-status ${status === "ready" ? "saved" : "loading"}`}>{status === "loading" ? "Loading…" : `${scheduled.length} scheduled`}</span></div>{status === "ready" && scheduled.length === 0 ? <section className="panel appointment-empty"><b>◫</b><h2>No upcoming appointments</h2><p>Add your next visit so preparation details stay close at hand.</p><button className="primary" onClick={onAdd}>Add appointment</button></section> : <div className="appointment-grid">{scheduled.map(item => <article className="appointment-card" key={item.id}><div className="appointment-card-head"><Badge kind="confirmed">Scheduled</Badge><span>{item.healthArea}</span></div><time>{when(item.startsAt)}</time><h2>{item.title}</h2><p>{[item.provider, item.facility].filter(Boolean).join(" · ") || "No provider recorded"}</p><small>{item.durationMinutes} minutes{item.location ? ` · ${item.location}` : ""}</small>{item.preparation && <div className="appointment-prep"><b>Preparation</b><span>{item.preparation}</span></div>}<div className="appointment-actions"><button className="secondary calendar-button" onClick={() => downloadAppointmentCalendar(item)}>＋ Calendar</button><button className="secondary" onClick={() => onEdit(item)}>Edit</button><button className="secondary" onClick={() => onStatus(item, "complete")}>Complete & add record</button><button className="text-button danger" onClick={() => onStatus(item, "cancel")}>Cancel</button></div></article>)}</div>}</section>{history.length > 0 && <section className="section-block"><div className="section-heading"><div><p className="section-label">HISTORY</p><h2>Past appointments</h2></div></div><section className="panel full appointment-history">{history.map(item => <div key={item.id}><span><Badge kind={item.status === "completed" ? "confirmed" : "upload"}>{item.status}</Badge><strong>{item.title}</strong></span><span>{when(item.startsAt)}</span><small>{[item.provider, item.facility].filter(Boolean).join(" · ")}</small></div>)}</section></section>}</>;
}
