"use client";
import { useState } from "react";
import type { Appointment } from "../lib/types";

type Draft = Omit<Appointment, "id" | "status">;
const blank: Draft = { title: "", healthArea: "Primary care", provider: "", facility: "", startsAt: "", durationMinutes: 30, location: "", preparation: "" };

export function AppointmentForm({ appointment, onSave, onClose }: { appointment: Appointment | null; onSave: (draft: Draft) => Promise<void>; onClose: () => void }) {
  const [draft, setDraft] = useState<Draft>(() => appointment ? { title: appointment.title, healthArea: appointment.healthArea, provider: appointment.provider, facility: appointment.facility, startsAt: appointment.startsAt, durationMinutes: appointment.durationMinutes, location: appointment.location, preparation: appointment.preparation } : blank);
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft(current => ({ ...current, [key]: value }));
  return <div className="modal-backdrop"><section className="record-modal" role="dialog" aria-modal="true" aria-labelledby="appointment-title"><div className="modal-head"><div><p className="section-label">CARE SCHEDULE</p><h2 id="appointment-title">{appointment ? "Edit appointment" : "Add appointment"}</h2></div><button aria-label="Close" onClick={onClose}>×</button></div><p className="form-guidance">Keep the practical details for an upcoming visit in one private place.</p><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(""); try { await onSave(draft); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save appointment."); setBusy(false); } }}><label>Appointment title<input required maxLength={140} value={draft.title} onChange={event => update("title", event.target.value)} placeholder="Annual physical" /></label><div className="form-row"><label>Health area<select value={draft.healthArea} onChange={event => update("healthArea", event.target.value)}>{["Primary care", "Dental", "Vision", "Specialist", "Laboratory", "Other"].map(area => <option key={area}>{area}</option>)}</select></label><label>Date and time<input required type="datetime-local" value={draft.startsAt} onChange={event => update("startsAt", event.target.value)} /></label></div><div className="form-row"><label>Provider<input value={draft.provider} onChange={event => update("provider", event.target.value)} placeholder="Dr. Maya Chen" /></label><label>Facility<input value={draft.facility} onChange={event => update("facility", event.target.value)} placeholder="Northside Dental" /></label></div><div className="form-row"><label>Duration in minutes<input required type="number" min={5} max={480} step={5} value={draft.durationMinutes} onChange={event => update("durationMinutes", Number(event.target.value))} /></label><label>Location<input value={draft.location} onChange={event => update("location", event.target.value)} placeholder="Office or telehealth link" /></label></div><label>Preparation notes<textarea rows={3} value={draft.preparation} onChange={event => update("preparation", event.target.value)} placeholder="Questions to ask, documents to bring, or fasting instructions" /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save appointment"}</button></div></form></section></div>;
}
