"use client";
import { useState } from "react";
import type { HealthProfile } from "../lib/types";

export function HealthProfileView({profile,status,error,onSave}:{profile:HealthProfile|null;status:"loading"|"ready"|"unavailable";error:string;onSave:(profile:Omit<HealthProfile,"reviewedAt">)=>Promise<void>}){
  if(status==="loading"||!profile)return <section className="panel profile-loading">{error||"Loading health essentials…"}</section>;
  return <HealthProfileEditor key={profile.reviewedAt} profile={profile} error={error} onSave={onSave}/>;
}
function HealthProfileEditor({profile,error,onSave}:{profile:HealthProfile;error:string;onSave:(profile:Omit<HealthProfile,"reviewedAt">)=>Promise<void>}){
  const[bloodType,setBloodType]=useState(profile.bloodType),[primaryProvider,setPrimaryProvider]=useState(profile.primaryProvider),[emergencyName,setEmergencyName]=useState(profile.emergencyName),[emergencyRelationship,setEmergencyRelationship]=useState(profile.emergencyRelationship),[emergencyPhone,setEmergencyPhone]=useState(profile.emergencyPhone),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  return <><header className="page-heading"><div><p className="kicker">IMPORTANT INFORMATION</p><h1>Health essentials</h1><p>Maintain a concise personal reference for appointments and emergencies.</p></div><span className="reviewed-date">Last reviewed {new Date(profile.reviewedAt).toLocaleDateString()}</span></header><div className="document-security"><span>!</span><div><strong>Patient-maintained information</strong><p>Medications, allergies, and conditions are managed in their dedicated sections. Confirm critical details with a qualified healthcare professional.</p></div><b>Private</b></div>{error&&<div className="data-notice">{error}</div>}<form className="essentials-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage("");try{await onSave({...profile,bloodType,primaryProvider,emergencyName,emergencyRelationship,emergencyPhone});setMessage("Health essentials saved.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to save.");}setBusy(false);}}><section className="panel essentials-section"><div><p className="section-label">PERSONAL SUMMARY</p><h2>Core details</h2><p>These fields appear in your personal health summary.</p></div><div className="essentials-grid"><label>Blood type<select value={bloodType} onChange={e=>setBloodType(e.target.value)}>{["","Unknown","A+","A-","B+","B-","AB+","AB-","O+","O-"].map(type=><option key={type} value={type}>{type||"Not recorded"}</option>)}</select></label><label>Primary care provider<input value={primaryProvider} onChange={e=>setPrimaryProvider(e.target.value)} placeholder="Provider name"/></label></div></section><section className="panel essentials-section"><div><p className="section-label">EMERGENCY CONTACT</p><h2>Who should be contacted?</h2></div><div className="emergency-grid"><label>Name<input value={emergencyName} onChange={e=>setEmergencyName(e.target.value)}/></label><label>Relationship<input value={emergencyRelationship} onChange={e=>setEmergencyRelationship(e.target.value)}/></label><label>Phone number<input type="tel" value={emergencyPhone} onChange={e=>setEmergencyPhone(e.target.value)}/></label></div></section><div className="essentials-save">{message&&<p className={message.includes("saved")?"auth-success":"form-error"}>{message}</p>}<button className="primary" disabled={busy}>{busy?"Saving…":"Save health essentials"}</button></div></form></>;
}
