import { healthAreas, recordCategories } from "../lib/demo-data";
import type { HealthDocument, HealthRecord, ViewId } from "../lib/types";
import { Badge, TimelineList } from "./ui";

export function HomeView({ setView, onAdd, onUpload }: { setView: (view: ViewId) => void; onAdd: () => void; onUpload: () => void }) {
  return <>
    <header className="page-heading"><div><p className="kicker">Saturday, August 15</p><h1>Good afternoon, Travis</h1><p>Your health history, organized around you.</p></div><div className="heading-actions"><button className="secondary" onClick={onUpload}>Upload document</button><button className="primary" onClick={onAdd}>＋ Add record</button></div></header>
    <section className="safety-card"><div className="safety-title"><span className="shield">✓</span><div><strong>Health essentials</strong><p>Reviewed August 2, 2026</p></div></div><div className="safety-facts"><div><span>ALLERGIES</span><strong>Penicillin</strong></div><div><span>CURRENT MEDICATIONS</span><strong>3 medications</strong></div><div><span>EMERGENCY CONTACT</span><strong>1 contact</strong></div></div><button className="text-button">Review profile →</button></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="section-label">NEXT APPOINTMENT</span><h2>Dental follow-up</h2></div><Badge kind="confirmed">Recorded</Badge></div><div className="appointment-body"><div className="date-block"><strong>24</strong><span>AUG</span></div><div><strong>10:30 AM · 45 minutes</strong><p>Dr. Maya Chen · Northside Dental</p><p>1200 Penn Avenue, Pittsburgh</p></div></div><div className="appointment-note"><span>Preparation</span><p>Bring updated insurance card and ask about sensitivity near tooth 19.</p></div><button className="wide-button">View appointment</button></section>
    <section className="panel quick-panel"><div className="panel-head"><h2>Quick actions</h2></div><button onClick={onAdd}>＋ <span><strong>Add health record</strong><small>Medication, condition, procedure, and more</small></span></button><button onClick={onUpload}>⇧ <span><strong>Upload a document</strong><small>PDF, image, or visit summary</small></span></button><button onClick={() => setView("timeline")}>◷ <span><strong>Review timeline</strong><small>See your full health history</small></span></button></section></div>
    <section className="section-block"><div className="section-heading"><div><p className="section-label">YOUR CARE</p><h2>Health areas</h2></div><button className="text-button">View all</button></div><div className="area-grid">{healthAreas.map((area) => <button className="area-card" key={area.name} onClick={() => area.destination && setView(area.destination)}><span className={`area-icon ${area.tone}`}>{area.code}</span><span><strong>{area.name}</strong><small>{area.detail}</small></span><span>›</span></button>)}</div></section>
    <section className="section-block"><div className="section-heading"><div><p className="section-label">RECENT</p><h2>Health activity</h2></div><button className="text-button" onClick={() => setView("timeline")}>Full timeline →</button></div><TimelineList compact /></section>
  </>;
}

export function TimelineView({ onAdd }: { onAdd: () => void }) { return <><header className="page-heading"><div><p className="kicker">YOUR COMPLETE HISTORY</p><h1>Health timeline</h1><p>Records from every area of your care, in one place.</p></div><button className="primary" onClick={onAdd}>＋ Add record</button></header><div className="filter-bar"><button>All dates⌄</button><button>All health areas⌄</button><button>All record types⌄</button><button>All sources⌄</button><button className="filter-search">⌕ Search timeline</button></div><section className="panel full"><div className="year-marker"><span>2026</span><div /></div><TimelineList /></section></>; }

export function DentalView() { return <><header className="page-heading"><div><p className="kicker">HEALTH AREA</p><h1>Dental care</h1><p>Your dentists, visits, procedures, imaging, and documents.</p></div><div className="heading-actions"><button className="secondary">Upload dental record</button><button className="primary">＋ Add dental record</button></div></header><section className="specialty-hero"><div><span className="area-icon teal large">DE</span><div><span className="section-label">CURRENT DENTIST</span><h2>Dr. Maya Chen</h2><p>Northside Dental · Last visit August 12, 2026</p></div></div><button className="wide-button">View provider</button></section><div className="metric-grid"><div><span>LAST CLEANING</span><strong>Aug 12, 2026</strong><small>Routine exam</small></div><div><span>NEXT VISIT</span><strong>Aug 24, 2026</strong><small>Follow-up</small></div><div><span>PROCEDURES</span><strong>4 recorded</strong><small>Since 2019</small></div><div><span>DOCUMENTS</span><strong>6 files</strong><small>2 X-rays</small></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Recent dental history</h2><button className="text-button">View all</button></div><TimelineList compact /></section><section className="panel"><div className="panel-head"><h2>Dental documents</h2></div>{[["PDF", "Treatment plan", "Aug 12, 2026 · Northside Dental"], ["IMG", "Dental X-ray · Tooth 19", "May 30, 2026 · Northside Dental"]].map((document) => <div className="doc-mini" key={document[1]}><span>{document[0]}</span><div><strong>{document[1]}</strong><small>{document[2]}</small></div></div>)}<button className="wide-button">Open document center</button></section></div></>; }

export function RecordsView({ records, status, error, onAdd, onEdit }: { records: HealthRecord[]; status: "loading" | "saved" | "demo"; error: string; onAdd: () => void; onEdit: (record: HealthRecord) => void }) { return <><header className="page-heading"><div><p className="kicker">STRUCTURED INFORMATION</p><h1>Records</h1><p>Review the information that makes up your health history.</p></div><button className="primary" onClick={onAdd}>＋ Add record</button></header><div className="record-grid">{recordCategories.map((category) => <button className="record-card" key={category.name}><span>{category.count}</span><strong>{category.name}</strong><small>View and manage records</small><b>→</b></button>)}</div><section className="section-block"><div className="section-heading"><div><p className="section-label">ENTERED BY YOU</p><h2>Personal records</h2></div><span className={`storage-status ${status}`}>{status === "loading" ? "Loading saved records…" : status === "saved" ? `${records.length} securely saved` : "Demo records"}</span></div>{error && status === "demo" && <div className="data-notice">Saved records are unavailable in this development view. Synthetic demo records are shown instead.</div>}<div className="personal-records">{records.map((record) => <article className="personal-record" key={record.id}><div><Badge kind="self">{record.type}</Badge><span>{new Date(`${record.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span></div><h3>{record.title}</h3><p>{record.provider || "No provider recorded"}</p><small>{record.notes || "No notes added."}</small><button className="text-button" onClick={() => onEdit(record)}>Edit record →</button></article>)}</div></section></>; }

export function DocumentsView({ documents, status, error, onUpload, onOpen }: { documents: HealthDocument[]; status: "loading" | "saved" | "unavailable"; error: string; onUpload: () => void; onOpen: (document: HealthDocument) => void }) { return <><header className="page-heading"><div><p className="kicker">ORIGINAL FILES</p><h1>Document center</h1><p>Securely organize files from every area of your care.</p></div><button className="primary" onClick={onUpload}>⇧ Upload documents</button></header><div className="document-security"><span>✓</span><div><strong>Private document vault</strong><p>Files are stored separately from searchable metadata and can only be opened by their owner.</p></div><b>{status === "loading" ? "Loading…" : status === "saved" ? `${documents.length} files` : "Unavailable"}</b></div><div className="filter-bar"><button>All documents⌄</button><button>All health areas⌄</button><button>All years⌄</button><button className="filter-search">⌕ Search documents</button></div>{error && status === "unavailable" && <div className="data-notice">Your saved documents could not be loaded in this development view.</div>}<section className="panel full"><div className="doc-row labels"><span>DOCUMENT</span><span>HEALTH AREA</span><span>DATE</span><span>SOURCE</span></div>{documents.length === 0 && status === "saved" ? <div className="empty-documents"><b>□</b><h2>No documents yet</h2><p>Upload a visit summary, treatment plan, X-ray, prescription, or lab report.</p><button className="primary" onClick={onUpload}>Upload your first document</button></div> : documents.map((document) => <button className="doc-row" key={document.id} onClick={() => onOpen(document)}><span><b className="file-icon">{document.contentType === "application/pdf" ? "PDF" : "IMG"}</b><span><strong>{document.title}</strong><small>{document.fileName} · {(document.sizeBytes / 1024 / 1024).toFixed(2)} MB</small></span></span><Badge>{document.healthArea}</Badge><span>{new Date(document.uploadedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span><Badge kind="upload">Uploaded</Badge></button>)}</section></>; }
