import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { clinicalFacts } from "../../../db/schema";
import { getCurrentUser } from "../../../db/current-user";
import { writeAuditEvent } from "../../../db/audit";
type Payload={id?:string;kind?:string;name?:string;severity?:string;reaction?:string;onsetDate?:string;status?:string;confirmingProvider?:string;notes?:string};
const kinds=new Set(["allergy","condition"]),severities=new Set(["mild","moderate","severe","unknown"]),statuses=new Set(["active","resolved","inactive"]);
function validate(payload:Payload){const kind=payload.kind?.trim()??"",name=payload.name?.trim()??"",severity=payload.severity?.trim()??"unknown",status=payload.status?.trim()??"active",onsetDate=payload.onsetDate?.trim()??"";if(!kinds.has(kind))return{error:"Choose allergy or condition."};if(!name||name.length>140)return{error:"Enter a name up to 140 characters."};if(!severities.has(severity)||!statuses.has(status))return{error:"Choose valid severity and status values."};if(onsetDate&&!/^\d{4}-\d{2}-\d{2}$/.test(onsetDate))return{error:"Enter a valid onset date."};return{value:{kind,name,severity,status,onsetDate,reaction:payload.reaction?.trim().slice(0,600)??"",confirmingProvider:payload.confirmingProvider?.trim().slice(0,160)??"",notes:payload.notes?.trim().slice(0,1200)??""}};}
const serialize=(row:typeof clinicalFacts.$inferSelect)=>({id:row.id,kind:row.kind,name:row.name,severity:row.severity,reaction:row.reaction,onsetDate:row.onsetDate,status:row.status,confirmingProvider:row.confirmingProvider,notes:row.notes});
export async function GET(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const rows=await(await getDb()).select().from(clinicalFacts).where(eq(clinicalFacts.ownerUserId,owner.id)).orderBy(asc(clinicalFacts.kind),asc(clinicalFacts.name));return Response.json({facts:rows.map(serialize)});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to load health details."},{status:500});}}
export async function POST(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const result=validate(await request.json() as Payload);if("error"in result)return Response.json({error:result.error},{status:400});const[row]=await(await getDb()).insert(clinicalFacts).values({id:crypto.randomUUID(),ownerUserId:owner.id,ownerEmail:owner.email,...result.value}).returning();await writeAuditEvent({ownerUserId:owner.id,ownerEmail:owner.email,action:"created",entityType:"clinical_fact",entityId:row.id,entityLabel:row.name});return Response.json({fact:serialize(row)},{status:201});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to add health detail."},{status:500});}}
export async function PUT(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const payload=await request.json() as Payload;if(!payload.id)return Response.json({error:"Health detail id is required."},{status:400});const result=validate(payload);if("error"in result)return Response.json({error:result.error},{status:400});const[row]=await(await getDb()).update(clinicalFacts).set({...result.value,updatedAt:new Date().toISOString()}).where(and(eq(clinicalFacts.id,payload.id),eq(clinicalFacts.ownerUserId,owner.id))).returning();if(!row)return Response.json({error:"Health detail not found."},{status:404});await writeAuditEvent({ownerUserId:owner.id,ownerEmail:owner.email,action:"updated",entityType:"clinical_fact",entityId:row.id,entityLabel:row.name});return Response.json({fact:serialize(row)});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to update health detail."},{status:500});}}
