"use client";

import { useState } from "react";

type View = "home" | "timeline" | "dental" | "records" | "documents";
const nav: { id: View; label: string; icon: string }[] = [
  { id: "home", label: "Home", icon: "⌂" }, { id: "timeline", label: "Timeline", icon: "◷" },
  { id: "records", label: "Records", icon: "▤" }, { id: "documents", label: "Documents", icon: "□" },
];
const timeline = [
  { date: "Aug 12, 2026", type: "Dental visit", title: "Routine exam and cleaning", provider: "Dr. Maya Chen · Northside Dental", source: "Entered by you", tone: "teal" },
  { date: "Jul 28, 2026", type: "Laboratory result", title: "Annual metabolic panel", provider: "Allegheny Health Lab", source: "Uploaded document", tone: "blue" },
  { date: "Jun 03, 2026", type: "Medication", title: "Amoxicillin 500 mg", provider: "Prescribed after dental procedure", source: "Entered by you", tone: "amber" },
  { date: "May 30, 2026", type: "Dental procedure", title: "Crown placed · Tooth 19", provider: "Dr. Maya Chen · Northside Dental", source: "Uploaded document", tone: "teal" },
];
const areas = [["Primary care","3 visits · 5 records","PC","blue"],["Dental","8 visits · 12 records","DE","teal"],["Vision","2 visits · 4 records","VI","purple"],["Specialists","4 providers · 9 records","SP","amber"],["Medications","3 current · 7 historical","RX","coral"],["Lab results","16 results","LB","green"]];

function Badge({children,kind="neutral"}:{children:React.ReactNode;kind?:string}){return <span className={`badge ${kind}`}>{children}</span>}
function TimelineList({compact=false}:{compact?:boolean}){return <div className="timeline-list">{timeline.map(item=><button className="timeline-item" key={item.title}><span className={`timeline-dot ${item.tone}`}/><span className="timeline-copy"><span className="eyebrow">{item.date} · {item.type}</span><strong>{item.title}</strong><span className="muted">{item.provider}</span>{!compact&&<Badge kind={item.source==="Entered by you"?"self":"upload"}>{item.source}</Badge>}</span><span className="chevron">›</span></button>)}</div>}

function HomeView({setView}:{setView:(v:View)=>void}){return <>
  <header className="page-heading"><div><p className="kicker">Saturday, August 15</p><h1>Good afternoon, Travis</h1><p>Your health history, organized around you.</p></div><div className="heading-actions"><button className="secondary">Upload document</button><button className="primary">＋ Add record</button></div></header>
  <section className="safety-card"><div className="safety-title"><span className="shield">✓</span><div><strong>Health essentials</strong><p>Reviewed August 2, 2026</p></div></div><div className="safety-facts"><div><span>ALLERGIES</span><strong>Penicillin</strong></div><div><span>CURRENT MEDICATIONS</span><strong>3 medications</strong></div><div><span>EMERGENCY CONTACT</span><strong>1 contact</strong></div></div><button className="text-button">Review profile →</button></section>
  <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="section-label">NEXT APPOINTMENT</span><h2>Dental follow-up</h2></div><Badge kind="confirmed">Recorded</Badge></div><div className="appointment-body"><div className="date-block"><strong>24</strong><span>AUG</span></div><div><strong>10:30 AM · 45 minutes</strong><p>Dr. Maya Chen · Northside Dental</p><p>1200 Penn Avenue, Pittsburgh</p></div></div><div className="appointment-note"><span>Preparation</span><p>Bring updated insurance card and ask about sensitivity near tooth 19.</p></div><button className="wide-button">View appointment</button></section>
  <section className="panel quick-panel"><div className="panel-head"><h2>Quick actions</h2></div><button>＋ <span><strong>Add health record</strong><small>Medication, condition, procedure, and more</small></span></button><button>⇧ <span><strong>Upload a document</strong><small>PDF, image, or visit summary</small></span></button><button onClick={()=>setView("timeline")}>◷ <span><strong>Review timeline</strong><small>See your full health history</small></span></button></section></div>
  <section className="section-block"><div className="section-heading"><div><p className="section-label">YOUR CARE</p><h2>Health areas</h2></div><button className="text-button">View all</button></div><div className="area-grid">{areas.map(([name,detail,code,tone])=><button className="area-card" key={name} onClick={()=>name==="Dental"&&setView("dental")}><span className={`area-icon ${tone}`}>{code}</span><span><strong>{name}</strong><small>{detail}</small></span><span>›</span></button>)}</div></section>
  <section className="section-block"><div className="section-heading"><div><p className="section-label">RECENT</p><h2>Health activity</h2></div><button className="text-button" onClick={()=>setView("timeline")}>Full timeline →</button></div><TimelineList compact/></section>
</>}
function TimelineView(){return <><header className="page-heading"><div><p className="kicker">YOUR COMPLETE HISTORY</p><h1>Health timeline</h1><p>Records from every area of your care, in one place.</p></div><button className="primary">＋ Add record</button></header><div className="filter-bar"><button>All dates⌄</button><button>All health areas⌄</button><button>All record types⌄</button><button>All sources⌄</button><button className="filter-search">⌕ Search timeline</button></div><section className="panel full"><div className="year-marker"><span>2026</span><div/></div><TimelineList/></section></>}
function DentalView(){return <><header className="page-heading"><div><p className="kicker">HEALTH AREA</p><h1>Dental care</h1><p>Your dentists, visits, procedures, imaging, and documents.</p></div><div className="heading-actions"><button className="secondary">Upload dental record</button><button className="primary">＋ Add dental record</button></div></header><section className="specialty-hero"><div><span className="area-icon teal large">DE</span><div><span className="section-label">CURRENT DENTIST</span><h2>Dr. Maya Chen</h2><p>Northside Dental · Last visit August 12, 2026</p></div></div><button className="wide-button">View provider</button></section><div className="metric-grid"><div><span>LAST CLEANING</span><strong>Aug 12, 2026</strong><small>Routine exam</small></div><div><span>NEXT VISIT</span><strong>Aug 24, 2026</strong><small>Follow-up</small></div><div><span>PROCEDURES</span><strong>4 recorded</strong><small>Since 2019</small></div><div><span>DOCUMENTS</span><strong>6 files</strong><small>2 X-rays</small></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Recent dental history</h2><button className="text-button">View all</button></div><TimelineList compact/></section><section className="panel"><div className="panel-head"><h2>Dental documents</h2></div>{[["PDF","Treatment plan","Aug 12, 2026 · Northside Dental"],["IMG","Dental X-ray · Tooth 19","May 30, 2026 · Northside Dental"]].map(d=><div className="doc-mini" key={d[1]}><span>{d[0]}</span><div><strong>{d[1]}</strong><small>{d[2]}</small></div></div>)}<button className="wide-button">Open document center</button></section></div></>}
function RecordsView(){return <><header className="page-heading"><div><p className="kicker">STRUCTURED INFORMATION</p><h1>Records</h1><p>Review the information that makes up your health history.</p></div><button className="primary">＋ Add record</button></header><div className="record-grid">{["Conditions","Allergies","Medications","Immunizations","Procedures","Measurements","Encounters","Diagnostic reports"].map((x,i)=><button className="record-card" key={x}><span>{[3,1,10,7,4,12,9,16][i]}</span><strong>{x}</strong><small>View and manage records</small><b>→</b></button>)}</div></>}
function DocumentsView(){return <><header className="page-heading"><div><p className="kicker">ORIGINAL FILES</p><h1>Document center</h1><p>Securely organize files from every area of your care.</p></div><button className="primary">⇧ Upload documents</button></header><div className="filter-bar"><button>All documents⌄</button><button>All health areas⌄</button><button>All years⌄</button><button className="filter-search">⌕ Search documents</button></div><section className="panel full"><div className="doc-row labels"><span>DOCUMENT</span><span>HEALTH AREA</span><span>DATE</span><span>SOURCE</span></div>{[["Treatment plan","Northside Dental · PDF","Dental","Aug 12, 2026"],["Annual metabolic panel","Allegheny Health Lab · PDF","Primary care","Jul 28, 2026"],["Dental X-ray · Tooth 19","Northside Dental · Image","Dental","May 30, 2026"],["Vision prescription","Oakland Vision Center · PDF","Vision","Jan 14, 2026"]].map(d=><button className="doc-row" key={d[0]}><span><b className="file-icon">▤</b><span><strong>{d[0]}</strong><small>{d[1]}</small></span></span><Badge>{d[2]}</Badge><span>{d[3]}</span><Badge kind="upload">Uploaded</Badge></button>)}</section></>}

export default function Page(){const[view,setView]=useState<View>("home");const[menu,setMenu]=useState(false);return <div className="app-shell"><aside className={menu?"sidebar open":"sidebar"}><div className="brand"><span>+</span><div><strong>PostCare</strong><small>Personal health record</small></div></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>{setView(n.id);setMenu(false)}}><span>{n.icon}</span>{n.label}</button>)}<button onClick={()=>{setView("dental");setMenu(false)}} className={view==="dental"?"active":""}><span>⌘</span>Health areas</button></nav><div className="sidebar-bottom"><button><span>♧</span>Access history</button><button><span>⚙</span>Settings</button><div className="profile"><span>TS</span><div><strong>Travis Skovira</strong><small>My health record</small></div><b>⋯</b></div></div></aside><main className="main"><div className="mobile-top"><button onClick={()=>setMenu(!menu)}>☰</button><div className="brand"><span>+</span><strong>PostCare</strong></div><button>⌕</button></div><div className="topbar"><label>⌕ <input placeholder="Search your health record"/></label><button aria-label="Notifications">♢</button><span className="privacy">● Private</span></div><div className="content">{view==="home"&&<HomeView setView={setView}/>} {view==="timeline"&&<TimelineView/>} {view==="dental"&&<DentalView/>} {view==="records"&&<RecordsView/>} {view==="documents"&&<DocumentsView/>}</div></main>{menu&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<nav className="mobile-nav"><button onClick={()=>setView("home")} className={view==="home"?"active":""}>⌂<span>Home</span></button><button onClick={()=>setView("timeline")} className={view==="timeline"?"active":""}>◷<span>Timeline</span></button><button className="add-mobile">＋<span>Add</span></button><button onClick={()=>setView("documents")} className={view==="documents"?"active":""}>□<span>Documents</span></button><button onClick={()=>setMenu(true)}>☰<span>More</span></button></nav></div>}
