import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { medications } from "../../../db/schema";
import { getCurrentUser } from "../../../db/current-user";
import { writeAuditEvent } from "../../../db/audit";

type Payload = { id?: string; name?: string; dosage?: string; frequency?: string; instructions?: string; prescribingProvider?: string; startDate?: string; endDate?: string; refillDate?: string; pharmacy?: string; status?: string; notes?: string };
const statuses = new Set(["active","completed","discontinued"]);
const date = (value?:string) => { const cleaned=value?.trim()??""; return cleaned===""||/^\d{4}-\d{2}-\d{2}$/.test(cleaned)?cleaned:null; };
function validate(payload:Payload){const name=payload.name?.trim()??"",status=payload.status?.trim()??"active",startDate=date(payload.startDate),endDate=date(payload.endDate),refillDate=date(payload.refillDate);if(!name||name.length>140)return{error:"Enter a medication name up to 140 characters."};if(!statuses.has(status))return{error:"Choose a valid medication status."};if(startDate===null||endDate===null||refillDate===null)return{error:"Enter valid medication dates."};return{value:{name,dosage:payload.dosage?.trim().slice(0,100)??"",frequency:payload.frequency?.trim().slice(0,160)??"",instructions:payload.instructions?.trim().slice(0,600)??"",prescribingProvider:payload.prescribingProvider?.trim().slice(0,160)??"",startDate,endDate,refillDate,pharmacy:payload.pharmacy?.trim().slice(0,160)??"",status,notes:payload.notes?.trim().slice(0,1200)??""}};}
const serialize=(row:typeof medications.$inferSelect)=>({id:row.id,name:row.name,dosage:row.dosage,frequency:row.frequency,instructions:row.instructions,prescribingProvider:row.prescribingProvider,startDate:row.startDate,endDate:row.endDate,refillDate:row.refillDate,pharmacy:row.pharmacy,status:row.status,notes:row.notes});

export async function GET(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const rows=await(await getDb()).select().from(medications).where(eq(medications.ownerUserId,owner.id)).orderBy(asc(medications.name));return Response.json({medications:rows.map(serialize)});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to load medications."},{status:500});}}
export async function POST(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const result=validate(await request.json() as Payload);if("error"in result)return Response.json({error:result.error},{status:400});const [row]=await(await getDb()).insert(medications).values({id:crypto.randomUUID(),ownerUserId:owner.id,ownerEmail:owner.email,...result.value}).returning();await writeAuditEvent({ownerUserId:owner.id,ownerEmail:owner.email,action:"created",entityType:"medication",entityId:row.id,entityLabel:row.name});return Response.json({medication:serialize(row)},{status:201});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to add medication."},{status:500});}}
export async function PUT(request:Request){try{const owner=await getCurrentUser(request);if(!owner)return Response.json({error:"Sign in is required."},{status:401});const payload=await request.json() as Payload;if(!payload.id)return Response.json({error:"Medication id is required."},{status:400});const result=validate(payload);if("error"in result)return Response.json({error:result.error},{status:400});const [row]=await(await getDb()).update(medications).set({...result.value,updatedAt:new Date().toISOString()}).where(and(eq(medications.id,payload.id),eq(medications.ownerUserId,owner.id))).returning();if(!row)return Response.json({error:"Medication not found."},{status:404});await writeAuditEvent({ownerUserId:owner.id,ownerEmail:owner.email,action:"updated",entityType:"medication",entityId:row.id,entityLabel:row.name});return Response.json({medication:serialize(row)});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to update medication."},{status:500});}}
